name: reveal-pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    name: Generate Pages
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: docs
          keep_files: true
